package pluralize

var plural_rules = map[string]string{
	`$`:                         "s",
	`s$`:                        "s",
	`^(ax|test)is$`:             "es",
	`(octop|vir)us$`:            "i",
	`(octop|vir)i$`:             "i",
	`(alias|status)$`:           "es",
	`(bu)s$`:                    "ses",
	`(buffal|tomat)o$`:          "oes",
	`([ti])um$`:                 "a",
	`([ti])a$`:                  "a",
	`(.+)sis$`:                  "ses",
	`(?:([^f])fe|([lr])f)$`:     "ves",
	`(hive)$`:                   "s",
	`([^aeiouy]|qu)y$`:          "ies",
	`(x|ch|ss|sh)$`:             "es",
	`(matr|vert|ind)(?:ix|ex)$`: "ices",
	`/^(m|l)ouse$`:              "ice",
	`^(m|l)ice$`:                "ice",
	`^(ox)$`:                    "en",
	`^(oxen)$`:                  "",
	`^(quiz)$`:                  "zes",
}
